server:
  port: 8003
  servlet:
    context-path: ""

spring:
  application:
    name: balance-settlement-service
  
  # Database configuration (H2 for development)
  datasource:
    url: jdbc:h2:mem:balancedb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  # H2 Console (for development debugging)
  h2:
    console:
      enabled: true
      path: /h2-console

# Jackson configuration for JSON handling
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# Logging configuration
logging:
  level:
    com.finshare.balance: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Application-specific configuration
finshare:
  balance:
    # Configuration for payment deep link generation
    payment-apps:
      gpay:
        base-url: "gpay://pay"
      paypal:
        base-url: "paypal://paypalme"
      venmo:
        base-url: "venmo://pay"
      cashapp:
        base-url: "cashapp://pay"
    
    # Cache configuration (for future Redis integration)
    cache:
      balance-ttl: 300 # 5 minutes
      debt-simplification-ttl: 600 # 10 minutes